/* Generated by auth-server bootstrap — do not edit by hand. */
window.APP_SPA_CONFIG = {
  issuer: "http://localhost:3000/api/auth",
  clientId: "RsipyYzAbfPVkzHItnMpmVwZuqblJloy",
  redirectUri: "http://localhost:3003/callback.html",
  nestVerifyUrl: "http://localhost:3004/auth/verify",
  nestExchangeUrl: "http://localhost:3004/auth/exchange",
  nestProfileUrl: "http://localhost:3004/demo/profile",
  signOutUrl: "http://localhost:3000/global-logout",
  scopes: "openid profile email",
};
